from __future__ import annotations
from typing import Protocol
from ..entities.forecast import ForecastItem, ForecastAggItem

class ForecastRepository(Protocol):
    def get_or_create_source(self, name: str, weight: float = 1.0) -> int: ...
    def add_forecasts(self, city: str, source_id: int, items: list[ForecastItem]) -> int: ...
    def list_forecasts(self, city: str, date: str | None = None) -> list[dict]: ...
    def save_aggregates(self, city: str, aggs: list[ForecastAggItem]) -> None: ...
    def list_aggregates(self, city: str, date: str | None = None) -> list[ForecastAggItem]: ...
