from __future__ import annotations
from typing import Protocol
from ..entities.user_prefs import UserPrefsData

class UserRepository(Protocol):
    def create_user(self, username: str, password: str) -> int: ...
    def authenticate(self, username: str, password: str) -> int | None: ...
    def get_user(self, user_id: int): ...
    def get_prefs(self, user_id: int) -> UserPrefsData: ...
    def update_prefs(self, user_id: int, prefs: UserPrefsData) -> None: ...
